<?php

/**
 * @file
 * Defines the Singles module.
 *
 * @category module
 */

/**
 * Implements hook_entity_operation_alter().
 * 
 * @param array $operations
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function singles_entity_operation_alter(array &$operations, \Drupal\Core\Entity\EntityInterface $entity)
{
    if ($entity->getEntityTypeId() == 'node') {
        if (\Drupal::service('singles')->getSingleByBundle($entity->bundle()) &&
            !\Drupal::currentUser()->hasPermission('administer singles')
        ) {
            if (!empty($operations['delete'])) {
                unset($operations['delete']);
            }
        }
    }
}
